services:
  app:
    build:
      context: .
      dockerfile: docker/Dockerfile
    container_name: "calliopen-webapp-{{BRANCH_NAME}}"
    restart: unless-stopped
    volumes:
      - .:/app
    labels:
      caddy: "{{DOMAIN}}"
      caddy.reverse_proxy: "{{upstreams 80}}"
    networks:
      - web

networks:
  web:
    name: web
    external: true