name: Deploy App

on:
  push:
    branches:
      - main
      - "**"

jobs:
  call-deploy:
    uses: tonsoo/deployer/.github/workflows/deploy.react.yml@main
    secrets:
      SSH_HOST: ${{ secrets.SSH_HOST }}
      SSH_PRIVATE_KEY: ${{ secrets.SSH_PRIVATE_KEY }}
      SSH_USER: ${{ secrets.SSH_USER }}
      DEPLOY_PATH: ${{ secrets.DEPLOY_PATH }}
    with:
      repo: tonsoo/calliopen-frontend
      app-name: calliopen
      domain: app.calliopen.com.br
      sub-domain: dev # Your dev branches will be accessible at branch.dev.example.com
      add-to-deploys: true # Will create an entry in your deploys lists
